n=input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(n))
print('É alfabético?',n.isalpha())
print('É número?', n.isnumeric())
print('É alfanumérico?',n.isalnum())
print('É decimal?',n.isdecimal())
print('Só tem espaços?',n.isspace())
print('Está em maiúsculas?',n.isupper())
print('Está em minúsculas?',n.islower())
print('Está capitalizado',n.isascii())
